version: '3.8'

services:
  app:
    build: .
    container_name: chatterbots-app
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: chatterbots-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert.pem:/etc/ssl/cert.pem
      - ./key.pem:/etc/ssl/key.pem
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
